apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  AMBIENTE: {{ .Values.config.ambiente | quote }}
  VERSION: {{ .Values.config.version | quote }}
  MENSAJE: {{ .Values.config.mensaje | quote }}
