apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-monitor
  labels:
    {{- include "mi-app-chart.labels" . | nindent 4 }}
    release: {{ .Values.prometheus.release }}
spec:
  selector:
    matchLabels:
      {{- include "mi-app-chart.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.prometheus.metricsPath }}
      interval: {{ .Values.prometheus.scrapeInterval }}
