environment: development

image:
  repository: mi-app
  tag: "1.0.0"
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  port: 80
  targetPort: 5000

resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

config:
  ambiente: "desarrollo"
  version: "1.0"
  mensaje: "Hola desde Kubernetes!"

prometheus:
  release: prometheus
  metricsPath: /metrics
  scrapeInterval: 15s
